---
- name: Clone a github repository
  become: yes
 # become_user: admin
  become_method: sudo
  git:
    repo: https://github.com/abergasov/ssh_notify
    dest: /home/admin/go/src/ssh_notify
    clone: yes
    update: yes

- name: Run install target
  timeout: 30
  #no_log: True
  become: yes
  become_method: sudo
  ansible.builtin.command: make name={{ server_name }} tg_token={{ tg_token }} tg_chat={{ tg_chat }} install
  args:
    chdir: /home/admin/go/src/ssh_notify
