# VPN
---
- hosts: "vpns"
  user: root
  vars_files:
    - secret
    - vars/main.yml
  become: true
  roles:
    - essentials
    - user
    - fail2ban
    - ssh_keys
    - ssh_notify
    - ssh
    - ufw
    - docker
    - vpns