---
- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install essential docker packages
  apt:
    name: docker-ce
    update_cache: yes
    cache_valid_time: 3600
    state: latest
  with_items:
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
    - docker-compose

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Adding docker users (for use without sudo)
  user:
    name: "{{ user }}"
    append: yes
    groups: docker
  become: true
