- name: Update apt repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes

- name: Check if a reboot is needed
  register: reboot_required_file
  stat: path=/var/run/reboot-required get_md5=no

- name: Reboot server
  reboot:
    msg: "Reboot initiated by Ansible due to kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  #when: reboot_required_file.stat.exists

## restore iptables
- name: Check wg route dropped
  become: yes
  become_method: sudo
  shell: iptables -t nat -L | grep 10.7.0.0/24
  ignore_errors: true
  register: wgip
  check_mode: no

- name: Restore wg routes
  become: yes
  become_method: sudo
  command: iptables -t nat -A POSTROUTING -s 10.7.0.0/24 ! -d 10.7.0.0/24 -j SNAT --to {{ ansible_host }}
  when: wgip.stdout == ""

- name: Check ovpn route dropped
  become: yes
  become_method: sudo
  shell: iptables -t nat -L | grep 10.8.0.0/24
  ignore_errors: true
  register: ovpnip
  check_mode: no

- name: Restore ovpn routes
  become: yes
  become_method: sudo
  command: iptables -t nat -A POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to {{ ansible_host }}
  when: ovpnip.stdout == ""
